$axure.loadCurrentPage({
  "url":"页面_2.html",
  "generationDate":new Date(1445698976794),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"d276a9431c0c419fbf672d2ad80f5dc0",
    "type":"Axure:Page",
    "name":"页面 2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b154c662d9524d56ab6f07b3929858c5",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSwipeRight":{
              "description":"OnSwipeRight",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 页面 1的副本",
                      "target":{
                        "targetType":"page",
                        "url":"页面_1的副本.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"57a08c7221c848a08df61bbbf0064f83",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0d1ad01fdc8e4748b11f0c4a8724dde5",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":375,
                      "height":647}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"52945de96542464fa4f9e5e7c88cb96d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":375,
                          "height":647}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_2/u1.png"}},
{
                  "id":"5c7a3e35f3eb40bb9a05f58f279a6141",
                  "label":"tab",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":94,
                      "y":597},
                    "size":{
                      "width":94,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF996699},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c18b1b6460fa44a19cf2dfae873864dc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":94,
                          "y":597},
                        "size":{
                          "width":94,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF996699},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_1的副本/tab_u30.png"}},
{
                  "id":"6e907630837e4cdba3699f993aeb9aca",
                  "label":"tab",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFE4E4E4},
{
                              "color":0xFFE4E4E4}]}},
                      "disabled":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFD7D7D7},
{
                          "color":0xFFD7D7D7}]},
                    "location":{
                      "x":0,
                      "y":597},
                    "size":{
                      "width":94,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e3af6e5b3f004b58b0aa8f91dc50f0ce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFE4E4E4},
{
                                  "color":0xFFE4E4E4}]}},
                          "disabled":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFD7D7D7},
{
                              "color":0xFFD7D7D7}]},
                        "location":{
                          "x":0,
                          "y":597},
                        "size":{
                          "width":94,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 页面 1的副本",
                              "target":{
                                "targetType":"page",
                                "url":"页面_1的副本.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/页面_1的副本/tab_u34.png",
                    "mouseOver~":"images/页面_1的副本/tab_u34_mouseOver.png",
                    "disabled~":"images/页面_1的副本/tab_u34.png"}},
{
                  "id":"a713f75acf1841f289ae2db3ce15c213",
                  "label":"tab",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFE4E4E4},
{
                              "color":0xFFE4E4E4}]}},
                      "disabled":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFD7D7D7},
{
                          "color":0xFFD7D7D7}]},
                    "location":{
                      "x":188,
                      "y":597},
                    "size":{
                      "width":94,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9a9060474d504992b51a97b5249a5129",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFE4E4E4},
{
                                  "color":0xFFE4E4E4}]}},
                          "disabled":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFD7D7D7},
{
                              "color":0xFFD7D7D7}]},
                        "location":{
                          "x":188,
                          "y":597},
                        "size":{
                          "width":94,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_1的副本/tab_u34.png",
                    "mouseOver~":"images/页面_1的副本/tab_u34_mouseOver.png",
                    "disabled~":"images/页面_1的副本/tab_u34.png"}},
{
                  "id":"e754818d863f4351a000633fa836d5d4",
                  "label":"tab",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFE4E4E4},
{
                              "color":0xFFE4E4E4}]}},
                      "disabled":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFD7D7D7},
{
                          "color":0xFFD7D7D7}]},
                    "location":{
                      "x":281,
                      "y":597},
                    "size":{
                      "width":94,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e946bdab489d4a72ad8f4a8f5cb48912",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFE4E4E4},
{
                                  "color":0xFFE4E4E4}]}},
                          "disabled":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFD7D7D7},
{
                              "color":0xFFD7D7D7}]},
                        "location":{
                          "x":281,
                          "y":597},
                        "size":{
                          "width":94,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_1的副本/tab_u34.png",
                    "mouseOver~":"images/页面_1的副本/tab_u34_mouseOver.png",
                    "disabled~":"images/页面_1的副本/tab_u34.png"}},
{
                  "id":"7ff8d504e04241729a95b4fe2e1f83c8",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":525},
                    "size":{
                      "width":83,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"620a0c4e8b3f4ee19847f1425d943cbf",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":198,
                      "y":525},
                    "size":{
                      "width":83,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"8c2a155f43e8407b8f8ac7c44a8eee42",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":282,
                      "y":525},
                    "size":{
                      "width":83,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"01b4087ddc1845ceb252dde07b031bdd",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"button",
                  "styleType":"button",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":6,
                      "y":543},
                    "size":{
                      "width":100,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"d6b57942a4a34628bae72106cf2b573e",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "size":{
                      "width":375,
                      "height":42}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"daf5aabf84094d8d80cde075845259d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "size":{
                          "width":375,
                          "height":42}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_1的副本/u24.png"}},
{
                  "id":"0cf820e017d047a1babedd241d41b3c4",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":146,
                      "y":11},
                    "size":{
                      "width":75,
                      "height":21},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"45e25c6901404f618687251f0884448c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":146,
                          "y":11},
                        "size":{
                          "width":75,
                          "height":21},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"dd2590beeb654ced943f222e7dff6d66",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":21,
                      "y":64},
                    "size":{
                      "width":70,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e352d82139fb4f02bf77febcbc2c353d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":21,
                          "y":64},
                        "size":{
                          "width":70,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_2/u19.jpg"}},
{
                  "id":"0c4df00bdebf436bba3c50e5e0a93f51",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":21,
                      "y":183},
                    "size":{
                      "width":70,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f1dd2cc760cd4e5da48888727e22c2af",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":21,
                          "y":183},
                        "size":{
                          "width":70,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_2/u21.jpg"}},
{
                  "id":"933abb9705714ad78a9ff50108d8dd04",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":21,
                      "y":300},
                    "size":{
                      "width":70,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ab3d3af8aa2f4f8d8cc982ccdcaa48e7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":21,
                          "y":300},
                        "size":{
                          "width":70,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_2/u23.jpg"}},
{
                  "id":"f19dacd67f5b4452b0baebfd360ea5e6",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":21,
                      "y":420},
                    "size":{
                      "width":70,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fd1f36d1c82b4e83bd4a960c54113d45",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":21,
                          "y":420},
                        "size":{
                          "width":70,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/页面_2/u25.jpg"}},
{
                  "id":"ebca9072bddd4f91ac0d184945511156",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":68},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d6e63f5657734a6387f89dbb45e523e3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":68},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"114dff7c14134ef4be7b55468aba193c",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":91},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a6a7a8c438d246efa344aa021e255967",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":91},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1bc8421a953a4511aaefa82f9184b5e0",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":114},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"726273c6ca4c41d39371fb12f6834d96",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":114},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b1f12347789a46ad920a0b81f4f39e98",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":187},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2fb0f5549c2a42c29c578bbf46f7d68d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":187},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"882c37150b2445dcbd3cd7e1e72ff807",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":210},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b42b80b6edd423d949ea04904026078",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":210},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1653fda0e3e0452c839f1d07e1b709ce",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":233},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"986509afc1e64975af295352aea7e856",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":233},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3e60231e296b4a4abc9e8b2250dd08c5",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":304},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dee6cf13bf2b495da436a1bfee3bd6ef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":304},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8712fd0e30f740f3a97a82d36ddc5377",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":327},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5c85316a93864e2a8c4427f7f6e51df9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":327},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d5c33eb1123b46f98bb507cbc1289d48",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":350},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eac239e07dde4ec7b7235bdd6afdf0b4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":350},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bbaec1e0d856488d8a15c49448500bb4",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":423},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"19c83620df764fd68210d1c88caa5fec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":423},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5605561b0a1e478bbeb3dabd06770e03",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":447},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e486e26605bc4ee99a49aba1a8610701",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":447},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9d7e49079964437a90e1080c16fe0d99",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":471},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a9def49b23a4ba087e3de2f2947c8e4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":471},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e6b873e8b703442ca1d02e89366faf16",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":508},
                    "size":{
                      "width":375,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/页面_2/u51_line.png"}},
{
                  "id":"5f08f686089d4166872beace7aaad2da",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":563},
                    "size":{
                      "width":83,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"1982fe215b7f488c9392d4d60f749b37",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":198,
                      "y":563},
                    "size":{
                      "width":83,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"5eae9138dae24de2afb2c0f4dc65b1a6",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":281,
                      "y":563},
                    "size":{
                      "width":83,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"6c04f450e0344ff195c172745739fc8a",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":393},
                    "size":{
                      "width":375,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/页面_2/u55_line.png"}},
{
                  "id":"09b439836f4348679716d757fb05f7b3",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":275},
                    "size":{
                      "width":375,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/页面_2/u55_line.png"}},
{
                  "id":"bee61c4ffa984a558591d95da5837937",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":155},
                    "size":{
                      "width":375,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/页面_2/u55_line.png"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "b154c662d9524d56ab6f07b3929858c5":{
      "scriptId":"u0"},
    "0d1ad01fdc8e4748b11f0c4a8724dde5":{
      "scriptId":"u1"},
    "52945de96542464fa4f9e5e7c88cb96d":{
      "scriptId":"u2"},
    "5c7a3e35f3eb40bb9a05f58f279a6141":{
      "scriptId":"u3"},
    "c18b1b6460fa44a19cf2dfae873864dc":{
      "scriptId":"u4"},
    "6e907630837e4cdba3699f993aeb9aca":{
      "scriptId":"u5"},
    "e3af6e5b3f004b58b0aa8f91dc50f0ce":{
      "scriptId":"u6"},
    "a713f75acf1841f289ae2db3ce15c213":{
      "scriptId":"u7"},
    "9a9060474d504992b51a97b5249a5129":{
      "scriptId":"u8"},
    "e754818d863f4351a000633fa836d5d4":{
      "scriptId":"u9"},
    "e946bdab489d4a72ad8f4a8f5cb48912":{
      "scriptId":"u10"},
    "7ff8d504e04241729a95b4fe2e1f83c8":{
      "scriptId":"u11"},
    "620a0c4e8b3f4ee19847f1425d943cbf":{
      "scriptId":"u12"},
    "8c2a155f43e8407b8f8ac7c44a8eee42":{
      "scriptId":"u13"},
    "01b4087ddc1845ceb252dde07b031bdd":{
      "scriptId":"u14"},
    "d6b57942a4a34628bae72106cf2b573e":{
      "scriptId":"u15"},
    "daf5aabf84094d8d80cde075845259d8":{
      "scriptId":"u16"},
    "0cf820e017d047a1babedd241d41b3c4":{
      "scriptId":"u17"},
    "45e25c6901404f618687251f0884448c":{
      "scriptId":"u18"},
    "dd2590beeb654ced943f222e7dff6d66":{
      "scriptId":"u19"},
    "e352d82139fb4f02bf77febcbc2c353d":{
      "scriptId":"u20"},
    "0c4df00bdebf436bba3c50e5e0a93f51":{
      "scriptId":"u21"},
    "f1dd2cc760cd4e5da48888727e22c2af":{
      "scriptId":"u22"},
    "933abb9705714ad78a9ff50108d8dd04":{
      "scriptId":"u23"},
    "ab3d3af8aa2f4f8d8cc982ccdcaa48e7":{
      "scriptId":"u24"},
    "f19dacd67f5b4452b0baebfd360ea5e6":{
      "scriptId":"u25"},
    "fd1f36d1c82b4e83bd4a960c54113d45":{
      "scriptId":"u26"},
    "ebca9072bddd4f91ac0d184945511156":{
      "scriptId":"u27"},
    "d6e63f5657734a6387f89dbb45e523e3":{
      "scriptId":"u28"},
    "114dff7c14134ef4be7b55468aba193c":{
      "scriptId":"u29"},
    "a6a7a8c438d246efa344aa021e255967":{
      "scriptId":"u30"},
    "1bc8421a953a4511aaefa82f9184b5e0":{
      "scriptId":"u31"},
    "726273c6ca4c41d39371fb12f6834d96":{
      "scriptId":"u32"},
    "b1f12347789a46ad920a0b81f4f39e98":{
      "scriptId":"u33"},
    "2fb0f5549c2a42c29c578bbf46f7d68d":{
      "scriptId":"u34"},
    "882c37150b2445dcbd3cd7e1e72ff807":{
      "scriptId":"u35"},
    "4b42b80b6edd423d949ea04904026078":{
      "scriptId":"u36"},
    "1653fda0e3e0452c839f1d07e1b709ce":{
      "scriptId":"u37"},
    "986509afc1e64975af295352aea7e856":{
      "scriptId":"u38"},
    "3e60231e296b4a4abc9e8b2250dd08c5":{
      "scriptId":"u39"},
    "dee6cf13bf2b495da436a1bfee3bd6ef":{
      "scriptId":"u40"},
    "8712fd0e30f740f3a97a82d36ddc5377":{
      "scriptId":"u41"},
    "5c85316a93864e2a8c4427f7f6e51df9":{
      "scriptId":"u42"},
    "d5c33eb1123b46f98bb507cbc1289d48":{
      "scriptId":"u43"},
    "eac239e07dde4ec7b7235bdd6afdf0b4":{
      "scriptId":"u44"},
    "bbaec1e0d856488d8a15c49448500bb4":{
      "scriptId":"u45"},
    "19c83620df764fd68210d1c88caa5fec":{
      "scriptId":"u46"},
    "5605561b0a1e478bbeb3dabd06770e03":{
      "scriptId":"u47"},
    "e486e26605bc4ee99a49aba1a8610701":{
      "scriptId":"u48"},
    "9d7e49079964437a90e1080c16fe0d99":{
      "scriptId":"u49"},
    "7a9def49b23a4ba087e3de2f2947c8e4":{
      "scriptId":"u50"},
    "e6b873e8b703442ca1d02e89366faf16":{
      "scriptId":"u51"},
    "5f08f686089d4166872beace7aaad2da":{
      "scriptId":"u52"},
    "1982fe215b7f488c9392d4d60f749b37":{
      "scriptId":"u53"},
    "5eae9138dae24de2afb2c0f4dc65b1a6":{
      "scriptId":"u54"},
    "6c04f450e0344ff195c172745739fc8a":{
      "scriptId":"u55"},
    "09b439836f4348679716d757fb05f7b3":{
      "scriptId":"u56"},
    "bee61c4ffa984a558591d95da5837937":{
      "scriptId":"u57"}}});