$axure.loadCurrentPage({
  "url":"消息.html",
  "generationDate":new Date(1445793807703.77),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"79f07668bb4142e2b0068b0b174f18f2",
    "type":"Axure:Page",
    "name":"消息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"823868c2866841bd99b9092e942d2dca",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":375,
              "height":647}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSwipeRight":{
              "description":"OnSwipeRight",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 交友",
                      "target":{
                        "targetType":"page",
                        "url":"交友.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"51c47e7c72114a8aa2e23f1dbb1971a1",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"6196219d44554651b9bb7145b499952d",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":375,
                      "height":647}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"67f804499001417c8f7dcd32bacba0da",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":375,
                          "height":647}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交友/u1.png"}},
{
                  "id":"ac720d9ad9944edfad8420bb9948ac54",
                  "label":"tab",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":188,
                      "y":597},
                    "size":{
                      "width":94,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF996699},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f4529f45ddad497582a21d6463c5d70a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":188,
                          "y":597},
                        "size":{
                          "width":94,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF996699},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/tab_u28.png"}},
{
                  "id":"4174c6f59bed4d3ca7621a5ee05aaba9",
                  "label":"tab",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFE4E4E4},
{
                              "color":0xFFE4E4E4}]}},
                      "disabled":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFD7D7D7},
{
                          "color":0xFFD7D7D7}]},
                    "location":{
                      "x":0,
                      "y":597},
                    "size":{
                      "width":94,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4f9fbad115fa4452895014ce9038c215",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFE4E4E4},
{
                                  "color":0xFFE4E4E4}]}},
                          "disabled":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFD7D7D7},
{
                              "color":0xFFD7D7D7}]},
                        "location":{
                          "x":0,
                          "y":597},
                        "size":{
                          "width":94,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 资讯",
                              "target":{
                                "targetType":"page",
                                "url":"资讯.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/资讯/tab_u32.png",
                    "mouseOver~":"images/资讯/tab_u32_mouseOver.png",
                    "disabled~":"images/资讯/tab_u32.png"}},
{
                  "id":"378e8b01ccce4b1bb9c1e40009c283f9",
                  "label":"tab",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFE4E4E4},
{
                              "color":0xFFE4E4E4}]}},
                      "disabled":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFD7D7D7},
{
                          "color":0xFFD7D7D7}]},
                    "location":{
                      "x":94,
                      "y":597},
                    "size":{
                      "width":94,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8efc86c975894e699db4aaeeca8f7df8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFE4E4E4},
{
                                  "color":0xFFE4E4E4}]}},
                          "disabled":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFD7D7D7},
{
                              "color":0xFFD7D7D7}]},
                        "location":{
                          "x":94,
                          "y":597},
                        "size":{
                          "width":94,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 交友",
                              "target":{
                                "targetType":"page",
                                "url":"交友.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/资讯/tab_u32.png",
                    "mouseOver~":"images/资讯/tab_u32_mouseOver.png",
                    "disabled~":"images/资讯/tab_u32.png"}},
{
                  "id":"090af12616894d5f9902fe185de70b80",
                  "label":"tab",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFE4E4E4},
{
                              "color":0xFFE4E4E4}]}},
                      "disabled":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFD7D7D7},
{
                          "color":0xFFD7D7D7}]},
                    "location":{
                      "x":281,
                      "y":597},
                    "size":{
                      "width":94,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4c6d23ddeb234fdfb92ad159acef5a51",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFE4E4E4},
{
                                  "color":0xFFE4E4E4}]}},
                          "disabled":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFD7D7D7},
{
                              "color":0xFFD7D7D7}]},
                        "location":{
                          "x":281,
                          "y":597},
                        "size":{
                          "width":94,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/tab_u32.png",
                    "mouseOver~":"images/资讯/tab_u32_mouseOver.png",
                    "disabled~":"images/资讯/tab_u32.png"}},
{
                  "id":"118010d137734ca891f6a5a82813978f",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "size":{
                      "width":375,
                      "height":42}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"af52006448b64860b64234fa36312868",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "size":{
                          "width":375,
                          "height":42}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/u24.png"}},
{
                  "id":"5de03aeffa4b43d0842a4b78d37b557d",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":146,
                      "y":11},
                    "size":{
                      "width":75,
                      "height":21},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8c5dc219311646fa9a820be5a958dde1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":146,
                          "y":11},
                        "size":{
                          "width":75,
                          "height":21},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"058115e59141470391f33be9bafdb910",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":21,
                      "y":45},
                    "size":{
                      "width":70,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"04609a7cd2e44951903a8c77004022b3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":21,
                          "y":45},
                        "size":{
                          "width":70,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/消息/u15.jpg"}},
{
                  "id":"dfde1a01a42d48e98dae89d8e723ec1b",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":21,
                      "y":123},
                    "size":{
                      "width":70,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bc6694df3c8449f38f27cea10367d7a1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":21,
                          "y":123},
                        "size":{
                          "width":70,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/消息/u17.png"}},
{
                  "id":"a1e6648ad51847c3a533dfefdfb01011",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":21,
                      "y":199},
                    "size":{
                      "width":70,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"feee14f0167b4355a3ebdaa63a6272f6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":21,
                          "y":199},
                        "size":{
                          "width":70,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交友/u22.jpg"}},
{
                  "id":"f77f17046ca8464aa79b4f6a597f48e5",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":115,
                      "y":50},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"47a49634972c4916a4abc9ed3e5f399b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":115,
                          "y":50},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"2b89d9e9299045d681c9b6f38fa64afd",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":267},
                    "size":{
                      "width":375,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/交友/u51_line.png"}},
{
                  "id":"79a847b9fd9341beb14f276f47a72e95",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":191},
                    "size":{
                      "width":375,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/交友/u51_line.png"}},
{
                  "id":"67b60a735b3644818e8049138596e6bc",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":114},
                    "size":{
                      "width":375,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/交友/u51_line.png"}},
{
                  "id":"a8b4b9507a9349b6b33aafd19a99160e",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":307,
                      "y":45},
                    "size":{
                      "width":58,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"c67ca55a03b44bef9ffc7d74bb6a33d6",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":113,
                      "y":90},
                    "size":{
                      "width":245,
                      "height":24}},
                  "adaptiveStyles":{
}},
{
                  "id":"f75f61741df6467abb1e20338408cc9b",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":113,
                      "y":67},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"a53a32a32921459eafb08fe1679f44ac",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":115,
                      "y":203},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"714261e629c346a095b0703e6d910dc8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":115,
                          "y":203},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"faea2b64dbaa4995827755a0ca9ac75b",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":325,
                      "y":198},
                    "size":{
                      "width":58,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"4eb3852f70db49ae85a69f8eef001656",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":113,
                      "y":243},
                    "size":{
                      "width":245,
                      "height":24}},
                  "adaptiveStyles":{
}},
{
                  "id":"fce22fe5cde6448c89d06066854013ad",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":113,
                      "y":220},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"961e5533ab5f471697befce68615de5a",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "location":{
                      "x":115,
                      "y":129},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3de724a73ece4c819dbc6a85e578d065",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"14px",
                        "location":{
                          "x":115,
                          "y":129},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"cda931c6f75f4005830436f223944fae",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"14px",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":315,
                      "y":123},
                    "size":{
                      "width":58,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"845b6a4077bf4c19b964526ac59cb5b7",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":113,
                      "y":168},
                    "size":{
                      "width":245,
                      "height":24}},
                  "adaptiveStyles":{
}},
{
                  "id":"7db09b0d84f7458d9066e9e7440560a5",
                  "label":"",
                  "parentDynamicPanel":"823868c2866841bd99b9092e942d2dca",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":113,
                      "y":146},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "823868c2866841bd99b9092e942d2dca":{
      "scriptId":"u0"},
    "6196219d44554651b9bb7145b499952d":{
      "scriptId":"u1"},
    "67f804499001417c8f7dcd32bacba0da":{
      "scriptId":"u2"},
    "ac720d9ad9944edfad8420bb9948ac54":{
      "scriptId":"u3"},
    "f4529f45ddad497582a21d6463c5d70a":{
      "scriptId":"u4"},
    "4174c6f59bed4d3ca7621a5ee05aaba9":{
      "scriptId":"u5"},
    "4f9fbad115fa4452895014ce9038c215":{
      "scriptId":"u6"},
    "378e8b01ccce4b1bb9c1e40009c283f9":{
      "scriptId":"u7"},
    "8efc86c975894e699db4aaeeca8f7df8":{
      "scriptId":"u8"},
    "090af12616894d5f9902fe185de70b80":{
      "scriptId":"u9"},
    "4c6d23ddeb234fdfb92ad159acef5a51":{
      "scriptId":"u10"},
    "118010d137734ca891f6a5a82813978f":{
      "scriptId":"u11"},
    "af52006448b64860b64234fa36312868":{
      "scriptId":"u12"},
    "5de03aeffa4b43d0842a4b78d37b557d":{
      "scriptId":"u13"},
    "8c5dc219311646fa9a820be5a958dde1":{
      "scriptId":"u14"},
    "058115e59141470391f33be9bafdb910":{
      "scriptId":"u15"},
    "04609a7cd2e44951903a8c77004022b3":{
      "scriptId":"u16"},
    "dfde1a01a42d48e98dae89d8e723ec1b":{
      "scriptId":"u17"},
    "bc6694df3c8449f38f27cea10367d7a1":{
      "scriptId":"u18"},
    "a1e6648ad51847c3a533dfefdfb01011":{
      "scriptId":"u19"},
    "feee14f0167b4355a3ebdaa63a6272f6":{
      "scriptId":"u20"},
    "f77f17046ca8464aa79b4f6a597f48e5":{
      "scriptId":"u21"},
    "47a49634972c4916a4abc9ed3e5f399b":{
      "scriptId":"u22"},
    "2b89d9e9299045d681c9b6f38fa64afd":{
      "scriptId":"u23"},
    "79a847b9fd9341beb14f276f47a72e95":{
      "scriptId":"u24"},
    "67b60a735b3644818e8049138596e6bc":{
      "scriptId":"u25"},
    "a8b4b9507a9349b6b33aafd19a99160e":{
      "scriptId":"u26"},
    "c67ca55a03b44bef9ffc7d74bb6a33d6":{
      "scriptId":"u27"},
    "f75f61741df6467abb1e20338408cc9b":{
      "scriptId":"u28"},
    "a53a32a32921459eafb08fe1679f44ac":{
      "scriptId":"u29"},
    "714261e629c346a095b0703e6d910dc8":{
      "scriptId":"u30"},
    "faea2b64dbaa4995827755a0ca9ac75b":{
      "scriptId":"u31"},
    "4eb3852f70db49ae85a69f8eef001656":{
      "scriptId":"u32"},
    "fce22fe5cde6448c89d06066854013ad":{
      "scriptId":"u33"},
    "961e5533ab5f471697befce68615de5a":{
      "scriptId":"u34"},
    "3de724a73ece4c819dbc6a85e578d065":{
      "scriptId":"u35"},
    "cda931c6f75f4005830436f223944fae":{
      "scriptId":"u36"},
    "845b6a4077bf4c19b964526ac59cb5b7":{
      "scriptId":"u37"},
    "7db09b0d84f7458d9066e9e7440560a5":{
      "scriptId":"u38"}}});