$axure.loadCurrentPage({
  "url":"home.html",
  "generationDate":new Date(1445783304845.04),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"0dd9fb22ec154b9b8e3228fa2c59f7af",
    "type":"Axure:Page",
    "name":"Home",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"用例 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"linkWindow",
                "description":"在 当前窗口 打开 等待",
                "target":{
                  "targetType":"page",
                  "url":"等待.html",
                  "includeVariables":true},
                "linkType":"current"}]}]}},
    "diagram":{
      "objects":[]}},
  "masters":{
},
  "objectPaths":{
}});