$axure.loadCurrentPage({
  "url":"资讯.html",
  "generationDate":new Date(1445793807333.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"ff3a6001b9654f27be7626558288488b",
    "type":"Axure:Page",
    "name":"资讯",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSwipeLeft":{
              "description":"OnSwipeLeft",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 交友",
                      "target":{
                        "targetType":"page",
                        "url":"交友.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"fdfec73709ec4c0790384eaeb9bfe027",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"3d07d42d8c9d441eb4f0a4be20600949",
                  "label":"",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":0,
                      "y":42},
                    "size":{
                      "width":375,
                      "height":605},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1ae84827ac2040fd97bd4315651857e3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":0,
                          "y":42},
                        "size":{
                          "width":375,
                          "height":605},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/u1.png"}},
{
                  "id":"7073b4a9fed54c2e9133a6b87d22f2df",
                  "label":"",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":537},
                    "size":{
                      "width":375,
                      "height":110},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2c2d2c44cb394edd9bb77a6441d833dd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":537},
                        "size":{
                          "width":375,
                          "height":110},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/u3.png"}},
{
                  "id":"bdf87ab02d0647368827950ab986e4d4",
                  "label":"",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":56},
                    "size":{
                      "width":375,
                      "height":164},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"71f3121761c84191b4fbf9292d60e0e1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":56},
                        "size":{
                          "width":375,
                          "height":164},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/u5.png"}},
{
                  "id":"3f38bc9c25834d02869900c8e7cb9401",
                  "label":"",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":230},
                    "size":{
                      "width":375,
                      "height":297},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9a749522e8dc49678641302550a1af23",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":230},
                        "size":{
                          "width":375,
                          "height":297},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/u7.png"}},
{
                  "id":"f53997a4dee3477d91829ef3b155e822",
                  "label":"paragraph",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "location":{
                      "x":156,
                      "y":10},
                    "size":{
                      "width":62,
                      "height":36},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"57b3518b3ad1411181cade1969030b01",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "location":{
                          "x":156,
                          "y":10},
                        "size":{
                          "width":62,
                          "height":36},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"67c38945585344ec8c62e6f0f16ff5c4",
                  "label":"image",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":6,
                      "y":54},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"071bc007ecb94516aa6faa9974978533",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":6,
                          "y":54},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/image_u11.jpg"}},
{
                  "id":"5a926ffda93946fb977bd9888e5977cb",
                  "label":"",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":46},
                    "size":{
                      "width":375,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/资讯/u13_line.png"}},
{
                  "id":"c0f3b9bfd21942b28e98d4765e97dbf2",
                  "label":"image",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":6,
                      "y":231},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ef73e24dd5024c699d55084ec8eb69f2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":6,
                          "y":231},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/image_u14.png"}},
{
                  "id":"64581c938cf245b39b4423ec9c027311",
                  "label":"image",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":6,
                      "y":537},
                    "size":{
                      "width":50,
                      "height":50}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1748714b02fd4b72ba748a566e3d02fb",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":6,
                          "y":537},
                        "size":{
                          "width":50,
                          "height":50}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/image_u16.png"}},
{
                  "id":"b9b560ba663b49d2a3207a86df136d03",
                  "label":"textfield",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":65,
                      "y":55},
                    "size":{
                      "width":220,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"d5c52a62311049be98ed79bea88c3460",
                  "label":"textfield",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":65,
                      "y":231},
                    "size":{
                      "width":220,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"88bc9668da4b405b9e31341a905b09a2",
                  "label":"textfield",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":65,
                      "y":538},
                    "size":{
                      "width":220,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"166763dda93a4b6da2a86350e4a3894e",
                  "label":"textfield",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":65,
                      "y":80},
                    "size":{
                      "width":220,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"6ca24fbc92654f5ba642ed792f3c05bd",
                  "label":"textfield",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":65,
                      "y":256},
                    "size":{
                      "width":220,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"25d80a1050c84a2bb5bd662669c0662e",
                  "label":"textfield",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":65,
                      "y":563},
                    "size":{
                      "width":220,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"53cc33e82e49439384a465370dba4dd8",
                  "label":"",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "size":{
                      "width":375,
                      "height":42}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d5e2af48caa048a2b615d9b3913bcc6b",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "size":{
                          "width":375,
                          "height":42}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/u24.png"}},
{
                  "id":"0aedae522f9a413a89fcd5cd8ff3fb36",
                  "label":"",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":146,
                      "y":11},
                    "size":{
                      "width":75,
                      "height":21},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a34407b06d4f44c2a465a75454885620",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":146,
                          "y":11},
                        "size":{
                          "width":75,
                          "height":21},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"ac431dba61ce4f18978b54a15604571e",
                  "label":"tab",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":0,
                      "y":597},
                    "size":{
                      "width":94,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF996699},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"43bf9ffe093f4ff39f918088ae5ddc59",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":0,
                          "y":597},
                        "size":{
                          "width":94,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF996699},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/tab_u28.png"}},
{
                  "id":"5b42d3f769f04887a9fc01a0aedf1f67",
                  "label":"tab",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFE4E4E4},
{
                              "color":0xFFE4E4E4}]}},
                      "disabled":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFD7D7D7},
{
                          "color":0xFFD7D7D7}]},
                    "location":{
                      "x":94.0000076293945,
                      "y":597},
                    "size":{
                      "width":94,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6daeba878c0a4ff4bacd176e21263c15",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFE4E4E4},
{
                                  "color":0xFFE4E4E4}]}},
                          "disabled":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFD7D7D7},
{
                              "color":0xFFD7D7D7}]},
                        "location":{
                          "x":94.0000076293945,
                          "y":597},
                        "size":{
                          "width":94,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 交友",
                              "target":{
                                "targetType":"page",
                                "url":"交友.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/资讯/tab_u30.png",
                    "mouseOver~":"images/资讯/tab_u30_mouseOver.png",
                    "disabled~":"images/资讯/tab_u30.png"}},
{
                  "id":"b5f63781dca241afa52a402700ff00b6",
                  "label":"tab",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFE4E4E4},
{
                              "color":0xFFE4E4E4}]}},
                      "disabled":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFD7D7D7},
{
                          "color":0xFFD7D7D7}]},
                    "location":{
                      "x":188,
                      "y":597},
                    "size":{
                      "width":94,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0d86369a7bb74dcf8c74a124a6e8b9fc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFE4E4E4},
{
                                  "color":0xFFE4E4E4}]}},
                          "disabled":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFD7D7D7},
{
                              "color":0xFFD7D7D7}]},
                        "location":{
                          "x":188,
                          "y":597},
                        "size":{
                          "width":94,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 消息",
                              "target":{
                                "targetType":"page",
                                "url":"消息.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/资讯/tab_u32.png",
                    "mouseOver~":"images/资讯/tab_u32_mouseOver.png",
                    "disabled~":"images/资讯/tab_u32.png"}},
{
                  "id":"c10c62cdff0a4f8e8826bc7179003400",
                  "label":"tab",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFE4E4E4},
{
                              "color":0xFFE4E4E4}]}},
                      "disabled":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFD7D7D7},
{
                          "color":0xFFD7D7D7}]},
                    "location":{
                      "x":281,
                      "y":597},
                    "size":{
                      "width":94,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bc521fb2ce994e37bd8f62af43e0f1fe",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFE4E4E4},
{
                                  "color":0xFFE4E4E4}]}},
                          "disabled":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFD7D7D7},
{
                              "color":0xFFD7D7D7}]},
                        "location":{
                          "x":281,
                          "y":597},
                        "size":{
                          "width":94,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/tab_u32.png",
                    "mouseOver~":"images/资讯/tab_u32_mouseOver.png",
                    "disabled~":"images/资讯/tab_u32.png"}},
{
                  "id":"481385f6d2694714a33f48f9976913d2",
                  "label":"",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "location":{
                      "x":6,
                      "y":114},
                    "size":{
                      "width":359,
                      "height":54},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"df451b189789438983b6ec409e9c6726",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "location":{
                          "x":6,
                          "y":114},
                        "size":{
                          "width":359,
                          "height":54},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8fd26589c9484bf896900a52b63a5dda",
                  "label":"click",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":145,
                      "y":602},
                    "size":{
                      "width":48,
                      "height":85}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onPanelStateChange":{
                      "description":"OnPanelStateChange",
                      "cases":[{
                          "description":"用例 2<br> (If state of click 等于 State1)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetPanelState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["8fd26589c9484bf896900a52b63a5dda"]}]},
                            "rightExpr":{
                              "exprType":"panelDiagramLiteral",
                              "panelPath":["8fd26589c9484bf896900a52b63a5dda"],
                              "panelIndex":0}},
                          "actions":[{
                              "action":"wait",
                              "description":"等待500毫秒",
                              "waitTime":500},
{
                              "action":"setPanelState",
                              "description":"设置 click to 状态2",
                              "panelsToStates":[{
                                  "panelPath":["8fd26589c9484bf896900a52b63a5dda"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]},
{
                          "description":"用例 2<br> (Else If state of click 等于 状态2)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetPanelState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["8fd26589c9484bf896900a52b63a5dda"]}]},
                            "rightExpr":{
                              "exprType":"panelDiagramLiteral",
                              "panelPath":["8fd26589c9484bf896900a52b63a5dda"],
                              "panelIndex":1}},
                          "actions":[{
                              "action":"wait",
                              "description":"等待500毫秒",
                              "waitTime":500},
{
                              "action":"setPanelState",
                              "description":"设置 click to 状态1",
                              "panelsToStates":[{
                                  "panelPath":["8fd26589c9484bf896900a52b63a5dda"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]},
{
                          "description":"用例 2<br> (Else If state of click 等于 状态1)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetPanelState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["8fd26589c9484bf896900a52b63a5dda"]}]},
                            "rightExpr":{
                              "exprType":"panelDiagramLiteral",
                              "panelPath":["8fd26589c9484bf896900a52b63a5dda"],
                              "panelIndex":2}},
                          "actions":[{
                              "action":"wait",
                              "description":"等待1000毫秒",
                              "waitTime":1000},
{
                              "action":"setPanelState",
                              "description":"设置 click to State1",
                              "panelsToStates":[{
                                  "panelPath":["8fd26589c9484bf896900a52b63a5dda"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]},
                    "onLoad":{
                      "description":"OnLoad",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"wait",
                              "description":"等待300毫秒",
                              "waitTime":300},
{
                              "action":"setPanelState",
                              "description":"设置 click to 状态2",
                              "panelsToStates":[{
                                  "panelPath":["8fd26589c9484bf896900a52b63a5dda"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"9c7a77ca78014810b8b35a28562f4185",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"966497af17da4565aa1f42462fdea2d0",
                          "label":"",
                          "parentDynamicPanel":"8fd26589c9484bf896900a52b63a5dda",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "baseStyle":"627587b6038d43cca051c114ac41ad32",
                            "location":{
                              "x":0,
                              "y":7},
                            "size":{
                              "width":48,
                              "height":78}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"be281aad2b3a46188beec5a992586b2c",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"8fd26589c9484bf896900a52b63a5dda",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                                "location":{
                                  "x":0,
                                  "y":7},
                                "size":{
                                  "width":48,
                                  "height":78}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/资讯/u39.png"}}]},
{
                      "id":"56619ecb03c441fa81545a4d9bf88435",
                      "label":"状态2",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"a4bded54f90e4742a6c97acfa3f56bf3",
                          "label":"",
                          "parentDynamicPanel":"8fd26589c9484bf896900a52b63a5dda",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "baseStyle":"627587b6038d43cca051c114ac41ad32",
                            "location":{
                              "x":0,
                              "y":8},
                            "size":{
                              "width":49,
                              "height":77}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"64ae7f8c5f6344218abf76051d01bded",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"8fd26589c9484bf896900a52b63a5dda",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                                "location":{
                                  "x":0,
                                  "y":8},
                                "size":{
                                  "width":49,
                                  "height":77}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/资讯/u41.png"}}]},
{
                      "id":"40534c2fa7cc443d90523695d04976fc",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"e7c7c660a2964b08ab10ef7bf4542f7e",
                          "label":"",
                          "parentDynamicPanel":"8fd26589c9484bf896900a52b63a5dda",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "baseStyle":"627587b6038d43cca051c114ac41ad32",
                            "size":{
                              "width":48,
                              "height":85}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"f975f8438ef748bd971c47f460993d68",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"8fd26589c9484bf896900a52b63a5dda",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                                "size":{
                                  "width":48,
                                  "height":85}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/资讯/u43.png"}}]}]},
{
                  "id":"207d98f28fe34b4b9134f567863af10d",
                  "label":"",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":183},
                    "size":{
                      "width":209,
                      "height":35}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6a8986f55a85455eaaeffbb142531dde",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":160,
                          "y":183},
                        "size":{
                          "width":209,
                          "height":35}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/u45.png"}},
{
                  "id":"0f315a861d494b0ca884e53fbc5ce6b5",
                  "label":"",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":160,
                      "y":490},
                    "size":{
                      "width":205,
                      "height":34}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a13d2226fd304f4e916273f5a3684d46",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":160,
                          "y":490},
                        "size":{
                          "width":205,
                          "height":34}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/u47.png"}},
{
                  "id":"351bafce0e664d58890506703d16f7e8",
                  "label":"",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":6,
                      "y":283},
                    "size":{
                      "width":354,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"c9e7e9bd470a43459461eb4c0254d57c",
                  "label":"",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0066FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":6,
                      "y":162},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"2b5bc345c4724ae38f44f9ee30ef6e24",
                  "label":"",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fontSize":"10px",
                    "location":{
                      "x":7,
                      "y":305},
                    "size":{
                      "width":184,
                      "height":15}},
                  "adaptiveStyles":{
}},
{
                  "id":"8d65aeccadc44f22b3f3d720be19eccf",
                  "label":"",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":330},
                    "size":{
                      "width":200,
                      "height":126}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9005809fa5eb4397baedaddc86983c66",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":10,
                          "y":330},
                        "size":{
                          "width":200,
                          "height":126}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/u52.jpg"}},
{
                  "id":"9043605854974d6a91116c05541dc926",
                  "label":"",
                  "parentDynamicPanel":"7fb23dfebb9f417fb8fe6e9eaa17ffd7",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0066FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":6,
                      "y":460},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "7fb23dfebb9f417fb8fe6e9eaa17ffd7":{
      "scriptId":"u0"},
    "3d07d42d8c9d441eb4f0a4be20600949":{
      "scriptId":"u1"},
    "1ae84827ac2040fd97bd4315651857e3":{
      "scriptId":"u2"},
    "7073b4a9fed54c2e9133a6b87d22f2df":{
      "scriptId":"u3"},
    "2c2d2c44cb394edd9bb77a6441d833dd":{
      "scriptId":"u4"},
    "bdf87ab02d0647368827950ab986e4d4":{
      "scriptId":"u5"},
    "71f3121761c84191b4fbf9292d60e0e1":{
      "scriptId":"u6"},
    "3f38bc9c25834d02869900c8e7cb9401":{
      "scriptId":"u7"},
    "9a749522e8dc49678641302550a1af23":{
      "scriptId":"u8"},
    "f53997a4dee3477d91829ef3b155e822":{
      "scriptId":"u9"},
    "57b3518b3ad1411181cade1969030b01":{
      "scriptId":"u10"},
    "67c38945585344ec8c62e6f0f16ff5c4":{
      "scriptId":"u11"},
    "071bc007ecb94516aa6faa9974978533":{
      "scriptId":"u12"},
    "5a926ffda93946fb977bd9888e5977cb":{
      "scriptId":"u13"},
    "c0f3b9bfd21942b28e98d4765e97dbf2":{
      "scriptId":"u14"},
    "ef73e24dd5024c699d55084ec8eb69f2":{
      "scriptId":"u15"},
    "64581c938cf245b39b4423ec9c027311":{
      "scriptId":"u16"},
    "1748714b02fd4b72ba748a566e3d02fb":{
      "scriptId":"u17"},
    "b9b560ba663b49d2a3207a86df136d03":{
      "scriptId":"u18"},
    "d5c52a62311049be98ed79bea88c3460":{
      "scriptId":"u19"},
    "88bc9668da4b405b9e31341a905b09a2":{
      "scriptId":"u20"},
    "166763dda93a4b6da2a86350e4a3894e":{
      "scriptId":"u21"},
    "6ca24fbc92654f5ba642ed792f3c05bd":{
      "scriptId":"u22"},
    "25d80a1050c84a2bb5bd662669c0662e":{
      "scriptId":"u23"},
    "53cc33e82e49439384a465370dba4dd8":{
      "scriptId":"u24"},
    "d5e2af48caa048a2b615d9b3913bcc6b":{
      "scriptId":"u25"},
    "0aedae522f9a413a89fcd5cd8ff3fb36":{
      "scriptId":"u26"},
    "a34407b06d4f44c2a465a75454885620":{
      "scriptId":"u27"},
    "ac431dba61ce4f18978b54a15604571e":{
      "scriptId":"u28"},
    "43bf9ffe093f4ff39f918088ae5ddc59":{
      "scriptId":"u29"},
    "5b42d3f769f04887a9fc01a0aedf1f67":{
      "scriptId":"u30"},
    "6daeba878c0a4ff4bacd176e21263c15":{
      "scriptId":"u31"},
    "b5f63781dca241afa52a402700ff00b6":{
      "scriptId":"u32"},
    "0d86369a7bb74dcf8c74a124a6e8b9fc":{
      "scriptId":"u33"},
    "c10c62cdff0a4f8e8826bc7179003400":{
      "scriptId":"u34"},
    "bc521fb2ce994e37bd8f62af43e0f1fe":{
      "scriptId":"u35"},
    "481385f6d2694714a33f48f9976913d2":{
      "scriptId":"u36"},
    "df451b189789438983b6ec409e9c6726":{
      "scriptId":"u37"},
    "8fd26589c9484bf896900a52b63a5dda":{
      "scriptId":"u38"},
    "966497af17da4565aa1f42462fdea2d0":{
      "scriptId":"u39"},
    "be281aad2b3a46188beec5a992586b2c":{
      "scriptId":"u40"},
    "a4bded54f90e4742a6c97acfa3f56bf3":{
      "scriptId":"u41"},
    "64ae7f8c5f6344218abf76051d01bded":{
      "scriptId":"u42"},
    "e7c7c660a2964b08ab10ef7bf4542f7e":{
      "scriptId":"u43"},
    "f975f8438ef748bd971c47f460993d68":{
      "scriptId":"u44"},
    "207d98f28fe34b4b9134f567863af10d":{
      "scriptId":"u45"},
    "6a8986f55a85455eaaeffbb142531dde":{
      "scriptId":"u46"},
    "0f315a861d494b0ca884e53fbc5ce6b5":{
      "scriptId":"u47"},
    "a13d2226fd304f4e916273f5a3684d46":{
      "scriptId":"u48"},
    "351bafce0e664d58890506703d16f7e8":{
      "scriptId":"u49"},
    "c9e7e9bd470a43459461eb4c0254d57c":{
      "scriptId":"u50"},
    "2b5bc345c4724ae38f44f9ee30ef6e24":{
      "scriptId":"u51"},
    "8d65aeccadc44f22b3f3d720be19eccf":{
      "scriptId":"u52"},
    "9005809fa5eb4397baedaddc86983c66":{
      "scriptId":"u53"},
    "9043605854974d6a91116c05541dc926":{
      "scriptId":"u54"}}});