$axure.loadCurrentPage({
  "url":"交友.html",
  "generationDate":new Date(1445783306363.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"CommentText"],
  "page":{
    "packageId":"d276a9431c0c419fbf672d2ad80f5dc0",
    "type":"Axure:Page",
    "name":"交友",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b154c662d9524d56ab6f07b3929858c5",
          "label":"",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "size":{
              "width":10,
              "height":10}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onSwipeLeft":{
              "description":"OnSwipeLeft",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 消息",
                      "target":{
                        "targetType":"page",
                        "url":"消息.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]},
            "onSwipeRight":{
              "description":"OnSwipeRight",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 资讯",
                      "target":{
                        "targetType":"page",
                        "url":"资讯.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"57a08c7221c848a08df61bbbf0064f83",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"0d1ad01fdc8e4748b11f0c4a8724dde5",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "size":{
                      "width":375,
                      "height":647}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"52945de96542464fa4f9e5e7c88cb96d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "size":{
                          "width":375,
                          "height":647}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交友/u1.png"}},
{
                  "id":"5c7a3e35f3eb40bb9a05f58f279a6141",
                  "label":"tab",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "location":{
                      "x":94,
                      "y":597},
                    "size":{
                      "width":94,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF996699},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c18b1b6460fa44a19cf2dfae873864dc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "location":{
                          "x":94,
                          "y":597},
                        "size":{
                          "width":94,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF996699},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/tab_u28.png"}},
{
                  "id":"6e907630837e4cdba3699f993aeb9aca",
                  "label":"tab",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFE4E4E4},
{
                              "color":0xFFE4E4E4}]}},
                      "disabled":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFD7D7D7},
{
                          "color":0xFFD7D7D7}]},
                    "location":{
                      "x":0,
                      "y":597},
                    "size":{
                      "width":94,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e3af6e5b3f004b58b0aa8f91dc50f0ce",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFE4E4E4},
{
                                  "color":0xFFE4E4E4}]}},
                          "disabled":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFD7D7D7},
{
                              "color":0xFFD7D7D7}]},
                        "location":{
                          "x":0,
                          "y":597},
                        "size":{
                          "width":94,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 资讯",
                              "target":{
                                "targetType":"page",
                                "url":"资讯.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/资讯/tab_u32.png",
                    "mouseOver~":"images/资讯/tab_u32_mouseOver.png",
                    "disabled~":"images/资讯/tab_u32.png"}},
{
                  "id":"a713f75acf1841f289ae2db3ce15c213",
                  "label":"tab",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFE4E4E4},
{
                              "color":0xFFE4E4E4}]}},
                      "disabled":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFD7D7D7},
{
                          "color":0xFFD7D7D7}]},
                    "location":{
                      "x":188,
                      "y":597},
                    "size":{
                      "width":94,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9a9060474d504992b51a97b5249a5129",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFE4E4E4},
{
                                  "color":0xFFE4E4E4}]}},
                          "disabled":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFD7D7D7},
{
                              "color":0xFFD7D7D7}]},
                        "location":{
                          "x":188,
                          "y":597},
                        "size":{
                          "width":94,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 消息",
                              "target":{
                                "targetType":"page",
                                "url":"消息.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/资讯/tab_u32.png",
                    "mouseOver~":"images/资讯/tab_u32_mouseOver.png",
                    "disabled~":"images/资讯/tab_u32.png"}},
{
                  "id":"e754818d863f4351a000633fa836d5d4",
                  "label":"tab",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF333333,
                      "opacity":1},
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "stateStyles":{
                      "mouseOver":{
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFFFFFFF},
{
                              "color":0xFFE4E4E4},
{
                              "color":0xFFE4E4E4}]}},
                      "disabled":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF999999,
                          "opacity":1}}},
                    "fill":{
                      "fillType":"linearGradient",
                      "colors":[{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFF2F2F2},
{
                          "color":0xFFD7D7D7},
{
                          "color":0xFFD7D7D7}]},
                    "location":{
                      "x":281,
                      "y":597},
                    "size":{
                      "width":94,
                      "height":50},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF999999},
                    "cornerRadiusTopLeft":"5"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e946bdab489d4a72ad8f4a8f5cb48912",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF333333,
                          "opacity":1},
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "stateStyles":{
                          "mouseOver":{
                            "fill":{
                              "fillType":"linearGradient",
                              "colors":[{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFFFFFFF},
{
                                  "color":0xFFE4E4E4},
{
                                  "color":0xFFE4E4E4}]}},
                          "disabled":{
                            "foreGroundFill":{
                              "fillType":"solid",
                              "color":0xFF999999,
                              "opacity":1}}},
                        "fill":{
                          "fillType":"linearGradient",
                          "colors":[{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFF2F2F2},
{
                              "color":0xFFD7D7D7},
{
                              "color":0xFFD7D7D7}]},
                        "location":{
                          "x":281,
                          "y":597},
                        "size":{
                          "width":94,
                          "height":50},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF999999},
                        "cornerRadiusTopLeft":"5"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/tab_u32.png",
                    "mouseOver~":"images/资讯/tab_u32_mouseOver.png",
                    "disabled~":"images/资讯/tab_u32.png"}},
{
                  "id":"7ff8d504e04241729a95b4fe2e1f83c8",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":10,
                      "y":562},
                    "size":{
                      "width":83,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"620a0c4e8b3f4ee19847f1425d943cbf",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":93,
                      "y":562},
                    "size":{
                      "width":83,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"8c2a155f43e8407b8f8ac7c44a8eee42",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"comboBox",
                  "styleType":"comboBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":177,
                      "y":562},
                    "size":{
                      "width":83,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"d6b57942a4a34628bae72106cf2b573e",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "baseStyle":"627587b6038d43cca051c114ac41ad32",
                    "size":{
                      "width":375,
                      "height":42}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"daf5aabf84094d8d80cde075845259d8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "baseStyle":"627587b6038d43cca051c114ac41ad32",
                        "size":{
                          "width":375,
                          "height":42}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/资讯/u24.png"}},
{
                  "id":"0cf820e017d047a1babedd241d41b3c4",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontName":"'微软雅黑 Bold', '微软雅黑'",
                    "fontSize":"16px",
                    "fontWeight":"700",
                    "horizontalAlignment":"center",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "location":{
                      "x":146,
                      "y":11},
                    "size":{
                      "width":75,
                      "height":21},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"45e25c6901404f618687251f0884448c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'微软雅黑 Bold', '微软雅黑'",
                        "fontSize":"16px",
                        "fontWeight":"700",
                        "horizontalAlignment":"center",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFFFFFF,
                          "opacity":1},
                        "location":{
                          "x":146,
                          "y":11},
                        "size":{
                          "width":75,
                          "height":21},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"dd2590beeb654ced943f222e7dff6d66",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":21,
                      "y":68},
                    "size":{
                      "width":70,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e352d82139fb4f02bf77febcbc2c353d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":21,
                          "y":68},
                        "size":{
                          "width":70,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交友/u18.jpg"}},
{
                  "id":"0c4df00bdebf436bba3c50e5e0a93f51",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":21,
                      "y":194},
                    "size":{
                      "width":70,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f1dd2cc760cd4e5da48888727e22c2af",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":21,
                          "y":194},
                        "size":{
                          "width":70,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交友/u20.jpg"}},
{
                  "id":"933abb9705714ad78a9ff50108d8dd04",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":21,
                      "y":322},
                    "size":{
                      "width":70,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ab3d3af8aa2f4f8d8cc982ccdcaa48e7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":21,
                          "y":322},
                        "size":{
                          "width":70,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交友/u22.jpg"}},
{
                  "id":"f19dacd67f5b4452b0baebfd360ea5e6",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":21,
                      "y":452},
                    "size":{
                      "width":70,
                      "height":70}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fd1f36d1c82b4e83bd4a960c54113d45",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":21,
                          "y":452},
                        "size":{
                          "width":70,
                          "height":70}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交友/u24.jpg"}},
{
                  "id":"ebca9072bddd4f91ac0d184945511156",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":60},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d6e63f5657734a6387f89dbb45e523e3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":60},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"114dff7c14134ef4be7b55468aba193c",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":83},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a6a7a8c438d246efa344aa021e255967",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":83},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1bc8421a953a4511aaefa82f9184b5e0",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":106},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"726273c6ca4c41d39371fb12f6834d96",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":106},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"b1f12347789a46ad920a0b81f4f39e98",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":189},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2fb0f5549c2a42c29c578bbf46f7d68d",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":189},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"882c37150b2445dcbd3cd7e1e72ff807",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":212},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"4b42b80b6edd423d949ea04904026078",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":212},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"1653fda0e3e0452c839f1d07e1b709ce",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":235},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"986509afc1e64975af295352aea7e856",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":235},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"3e60231e296b4a4abc9e8b2250dd08c5",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":317},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dee6cf13bf2b495da436a1bfee3bd6ef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":317},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"8712fd0e30f740f3a97a82d36ddc5377",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":340},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5c85316a93864e2a8c4427f7f6e51df9",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":340},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"d5c33eb1123b46f98bb507cbc1289d48",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":363},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eac239e07dde4ec7b7235bdd6afdf0b4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":363},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bbaec1e0d856488d8a15c49448500bb4",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":445},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"19c83620df764fd68210d1c88caa5fec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":445},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5605561b0a1e478bbeb3dabd06770e03",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":469},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"e486e26605bc4ee99a49aba1a8610701",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":469},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"9d7e49079964437a90e1080c16fe0d99",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":115,
                      "y":493},
                    "size":{
                      "width":150,
                      "height":16},
                    "rotation":"0",
                    "textRotation":"0"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7a9def49b23a4ba087e3de2f2947c8e4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":115,
                          "y":493},
                        "size":{
                          "width":150,
                          "height":16},
                        "rotation":"0",
                        "textRotation":"0"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"e6b873e8b703442ca1d02e89366faf16",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":545},
                    "size":{
                      "width":375,
                      "height":10}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/交友/u50_line.png"}},
{
                  "id":"6c04f450e0344ff195c172745739fc8a",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":417},
                    "size":{
                      "width":375,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/交友/u51_line.png"}},
{
                  "id":"09b439836f4348679716d757fb05f7b3",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":291},
                    "size":{
                      "width":375,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/交友/u51_line.png"}},
{
                  "id":"bee61c4ffa984a558591d95da5837937",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":161},
                    "size":{
                      "width":375,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFAEAEAE}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/交友/u51_line.png"}},
{
                  "id":"a91e102d9efe40ef807bf7ae3e8d3278",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":348,
                      "y":561},
                    "size":{
                      "width":25,
                      "height":25},
                    "borderWidth":"-1",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFF000000}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8dfca7fd6a1340dabe4b20ec6caba7ef",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":348,
                          "y":561},
                        "size":{
                          "width":25,
                          "height":25},
                        "borderWidth":"-1",
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFF000000}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/交友/u54.png"}},
{
                  "id":"febe807958084162893f04fb04398e4e",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":295,
                      "y":561},
                    "size":{
                      "width":60,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"816f596935f7443281d1454111942874",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":112,
                      "y":125},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"6a2957a07fbf4b238bff34f1897ebd38",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":112,
                      "y":255},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"4151184bc91a49d69d7c3028e4ff9883",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":112,
                      "y":382},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"9e1ef4cd47444e1ab6705a74f3b94087",
                  "label":"",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"textBox",
                  "styleType":"textBox",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF0099FF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFFFFF},
                    "location":{
                      "x":112,
                      "y":513},
                    "size":{
                      "width":200,
                      "height":25}},
                  "adaptiveStyles":{
}},
{
                  "id":"9e1454e5693a490ca86de9733b63be69",
                  "label":"click",
                  "parentDynamicPanel":"b154c662d9524d56ab6f07b3929858c5",
                  "type":"dynamicPanel",
                  "styleType":"dynamicPanel",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":234,
                      "y":593},
                    "size":{
                      "width":48,
                      "height":85}},
                  "adaptiveStyles":{
},
                  "interactionMap":{
                    "onPanelStateChange":{
                      "description":"OnPanelStateChange",
                      "cases":[{
                          "description":"用例 2<br> (If state of click 等于 State1)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetPanelState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["9e1454e5693a490ca86de9733b63be69"]}]},
                            "rightExpr":{
                              "exprType":"panelDiagramLiteral",
                              "panelPath":["9e1454e5693a490ca86de9733b63be69"],
                              "panelIndex":0}},
                          "actions":[{
                              "action":"wait",
                              "description":"等待500毫秒",
                              "waitTime":500},
{
                              "action":"setPanelState",
                              "description":"设置 click to 状态2",
                              "panelsToStates":[{
                                  "panelPath":["9e1454e5693a490ca86de9733b63be69"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]},
{
                          "description":"用例 2<br> (Else If state of click 等于 状态2)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetPanelState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["9e1454e5693a490ca86de9733b63be69"]}]},
                            "rightExpr":{
                              "exprType":"panelDiagramLiteral",
                              "panelPath":["9e1454e5693a490ca86de9733b63be69"],
                              "panelIndex":1}},
                          "actions":[{
                              "action":"wait",
                              "description":"等待500毫秒",
                              "waitTime":500},
{
                              "action":"setPanelState",
                              "description":"设置 click to 状态1",
                              "panelsToStates":[{
                                  "panelPath":["9e1454e5693a490ca86de9733b63be69"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":3,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]},
{
                          "description":"用例 2<br> (Else If state of click 等于 状态1)",
                          "isNewIfGroup":false,
                          "condition":{
                            "exprType":"binaryOp",
                            "op":"==",
                            "leftExpr":{
                              "exprType":"fcall",
                              "functionName":"GetPanelState",
                              "arguments":[{
                                  "exprType":"pathLiteral",
                                  "isThis":false,
                                  "isFocused":false,
                                  "isTarget":false,
                                  "value":["9e1454e5693a490ca86de9733b63be69"]}]},
                            "rightExpr":{
                              "exprType":"panelDiagramLiteral",
                              "panelPath":["9e1454e5693a490ca86de9733b63be69"],
                              "panelIndex":2}},
                          "actions":[{
                              "action":"wait",
                              "description":"等待1000毫秒",
                              "waitTime":1000},
{
                              "action":"setPanelState",
                              "description":"设置 click to State1",
                              "panelsToStates":[{
                                  "panelPath":["9e1454e5693a490ca86de9733b63be69"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":1,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]},
                    "onLoad":{
                      "description":"OnLoad",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"wait",
                              "description":"等待300毫秒",
                              "waitTime":300},
{
                              "action":"setPanelState",
                              "description":"设置 click to 状态2",
                              "panelsToStates":[{
                                  "panelPath":["9e1454e5693a490ca86de9733b63be69"],
                                  "stateInfo":{
                                    "setStateType":"diagram",
                                    "stateNumber":2,
                                    "stateValue":{
                                      "exprType":"stringLiteral",
                                      "value":"1",
                                      "stos":[]},
                                    "loop":false,
                                    "showWhenSet":false,
                                    "options":{
                                      "compress":false}}}]}]}]}},
                  "scrollbars":"none",
                  "fitToContent":false,
                  "propagate":false,
                  "diagrams":[{
                      "id":"0c41e9c556524142bd6853b1db79b091",
                      "label":"State1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"f664b8d379134776ae60bdccc55452e0",
                          "label":"",
                          "parentDynamicPanel":"9e1454e5693a490ca86de9733b63be69",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "baseStyle":"627587b6038d43cca051c114ac41ad32",
                            "location":{
                              "x":0,
                              "y":7},
                            "size":{
                              "width":48,
                              "height":78}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"18f3b27effbb4a818cbfdc80b03bc982",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"9e1454e5693a490ca86de9733b63be69",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                                "location":{
                                  "x":0,
                                  "y":7},
                                "size":{
                                  "width":48,
                                  "height":78}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/资讯/u39.png"}}]},
{
                      "id":"2243b871f23d44749b20f4135421346c",
                      "label":"状态2",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"ded33b8c7f5440d395535130c830010a",
                          "label":"",
                          "parentDynamicPanel":"9e1454e5693a490ca86de9733b63be69",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "baseStyle":"627587b6038d43cca051c114ac41ad32",
                            "location":{
                              "x":0,
                              "y":8},
                            "size":{
                              "width":49,
                              "height":77}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"ee29b79ab5f34007aadc15e0ce3fa200",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"9e1454e5693a490ca86de9733b63be69",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                                "location":{
                                  "x":0,
                                  "y":8},
                                "size":{
                                  "width":49,
                                  "height":77}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/资讯/u41.png"}}]},
{
                      "id":"8b59119ec534419c979aa7ba2bba152a",
                      "label":"状态1",
                      "type":"Axure:PanelDiagram",
                      "objects":[{
                          "id":"49844708777149baa7e33fe114abb69c",
                          "label":"",
                          "parentDynamicPanel":"9e1454e5693a490ca86de9733b63be69",
                          "type":"imageBox",
                          "styleType":"imageBox",
                          "visible":true,
                          "style":{
                            "baseStyle":"627587b6038d43cca051c114ac41ad32",
                            "size":{
                              "width":48,
                              "height":85}},
                          "adaptiveStyles":{
},
                          "objects":[{
                              "id":"2b1f9fcf1fea4b64840e7436b263fb3e",
                              "label":"",
                              "isContained":true,
                              "parentDynamicPanel":"9e1454e5693a490ca86de9733b63be69",
                              "type":"richTextPanel",
                              "styleType":"paragraph",
                              "visible":true,
                              "style":{
                                "baseStyle":"627587b6038d43cca051c114ac41ad32",
                                "size":{
                                  "width":48,
                                  "height":85}},
                              "adaptiveStyles":{
}}],
                          "images":{
                            "normal~":"images/资讯/u43.png"}}]}]}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "b154c662d9524d56ab6f07b3929858c5":{
      "scriptId":"u0"},
    "0d1ad01fdc8e4748b11f0c4a8724dde5":{
      "scriptId":"u1"},
    "52945de96542464fa4f9e5e7c88cb96d":{
      "scriptId":"u2"},
    "5c7a3e35f3eb40bb9a05f58f279a6141":{
      "scriptId":"u3"},
    "c18b1b6460fa44a19cf2dfae873864dc":{
      "scriptId":"u4"},
    "6e907630837e4cdba3699f993aeb9aca":{
      "scriptId":"u5"},
    "e3af6e5b3f004b58b0aa8f91dc50f0ce":{
      "scriptId":"u6"},
    "a713f75acf1841f289ae2db3ce15c213":{
      "scriptId":"u7"},
    "9a9060474d504992b51a97b5249a5129":{
      "scriptId":"u8"},
    "e754818d863f4351a000633fa836d5d4":{
      "scriptId":"u9"},
    "e946bdab489d4a72ad8f4a8f5cb48912":{
      "scriptId":"u10"},
    "7ff8d504e04241729a95b4fe2e1f83c8":{
      "scriptId":"u11"},
    "620a0c4e8b3f4ee19847f1425d943cbf":{
      "scriptId":"u12"},
    "8c2a155f43e8407b8f8ac7c44a8eee42":{
      "scriptId":"u13"},
    "d6b57942a4a34628bae72106cf2b573e":{
      "scriptId":"u14"},
    "daf5aabf84094d8d80cde075845259d8":{
      "scriptId":"u15"},
    "0cf820e017d047a1babedd241d41b3c4":{
      "scriptId":"u16"},
    "45e25c6901404f618687251f0884448c":{
      "scriptId":"u17"},
    "dd2590beeb654ced943f222e7dff6d66":{
      "scriptId":"u18"},
    "e352d82139fb4f02bf77febcbc2c353d":{
      "scriptId":"u19"},
    "0c4df00bdebf436bba3c50e5e0a93f51":{
      "scriptId":"u20"},
    "f1dd2cc760cd4e5da48888727e22c2af":{
      "scriptId":"u21"},
    "933abb9705714ad78a9ff50108d8dd04":{
      "scriptId":"u22"},
    "ab3d3af8aa2f4f8d8cc982ccdcaa48e7":{
      "scriptId":"u23"},
    "f19dacd67f5b4452b0baebfd360ea5e6":{
      "scriptId":"u24"},
    "fd1f36d1c82b4e83bd4a960c54113d45":{
      "scriptId":"u25"},
    "ebca9072bddd4f91ac0d184945511156":{
      "scriptId":"u26"},
    "d6e63f5657734a6387f89dbb45e523e3":{
      "scriptId":"u27"},
    "114dff7c14134ef4be7b55468aba193c":{
      "scriptId":"u28"},
    "a6a7a8c438d246efa344aa021e255967":{
      "scriptId":"u29"},
    "1bc8421a953a4511aaefa82f9184b5e0":{
      "scriptId":"u30"},
    "726273c6ca4c41d39371fb12f6834d96":{
      "scriptId":"u31"},
    "b1f12347789a46ad920a0b81f4f39e98":{
      "scriptId":"u32"},
    "2fb0f5549c2a42c29c578bbf46f7d68d":{
      "scriptId":"u33"},
    "882c37150b2445dcbd3cd7e1e72ff807":{
      "scriptId":"u34"},
    "4b42b80b6edd423d949ea04904026078":{
      "scriptId":"u35"},
    "1653fda0e3e0452c839f1d07e1b709ce":{
      "scriptId":"u36"},
    "986509afc1e64975af295352aea7e856":{
      "scriptId":"u37"},
    "3e60231e296b4a4abc9e8b2250dd08c5":{
      "scriptId":"u38"},
    "dee6cf13bf2b495da436a1bfee3bd6ef":{
      "scriptId":"u39"},
    "8712fd0e30f740f3a97a82d36ddc5377":{
      "scriptId":"u40"},
    "5c85316a93864e2a8c4427f7f6e51df9":{
      "scriptId":"u41"},
    "d5c33eb1123b46f98bb507cbc1289d48":{
      "scriptId":"u42"},
    "eac239e07dde4ec7b7235bdd6afdf0b4":{
      "scriptId":"u43"},
    "bbaec1e0d856488d8a15c49448500bb4":{
      "scriptId":"u44"},
    "19c83620df764fd68210d1c88caa5fec":{
      "scriptId":"u45"},
    "5605561b0a1e478bbeb3dabd06770e03":{
      "scriptId":"u46"},
    "e486e26605bc4ee99a49aba1a8610701":{
      "scriptId":"u47"},
    "9d7e49079964437a90e1080c16fe0d99":{
      "scriptId":"u48"},
    "7a9def49b23a4ba087e3de2f2947c8e4":{
      "scriptId":"u49"},
    "e6b873e8b703442ca1d02e89366faf16":{
      "scriptId":"u50"},
    "6c04f450e0344ff195c172745739fc8a":{
      "scriptId":"u51"},
    "09b439836f4348679716d757fb05f7b3":{
      "scriptId":"u52"},
    "bee61c4ffa984a558591d95da5837937":{
      "scriptId":"u53"},
    "a91e102d9efe40ef807bf7ae3e8d3278":{
      "scriptId":"u54"},
    "8dfca7fd6a1340dabe4b20ec6caba7ef":{
      "scriptId":"u55"},
    "febe807958084162893f04fb04398e4e":{
      "scriptId":"u56"},
    "816f596935f7443281d1454111942874":{
      "scriptId":"u57"},
    "6a2957a07fbf4b238bff34f1897ebd38":{
      "scriptId":"u58"},
    "4151184bc91a49d69d7c3028e4ff9883":{
      "scriptId":"u59"},
    "9e1ef4cd47444e1ab6705a74f3b94087":{
      "scriptId":"u60"},
    "9e1454e5693a490ca86de9733b63be69":{
      "scriptId":"u61"},
    "f664b8d379134776ae60bdccc55452e0":{
      "scriptId":"u62"},
    "18f3b27effbb4a818cbfdc80b03bc982":{
      "scriptId":"u63"},
    "ded33b8c7f5440d395535130c830010a":{
      "scriptId":"u64"},
    "ee29b79ab5f34007aadc15e0ce3fa200":{
      "scriptId":"u65"},
    "49844708777149baa7e33fe114abb69c":{
      "scriptId":"u66"},
    "2b1f9fcf1fea4b64840e7436b263fb3e":{
      "scriptId":"u67"}}});